packages:
  - 'apps/*'
  - 'packages/*'

engineStrict: true
strictPeerDependencies: true
savePrefix: ''
pmOnFail: error
minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  'sharp@0.34.5': true
  'unrs-resolver@1.12.2': true
